import { Archive, CalendarDays, Plus, RotateCcw, Target } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { goalProgress } from '../../domain/financePlanning'
import { parseRinggitToSen } from '../../lib/format'
import { usePrivacyLock } from '../../privacy/usePrivacyLock'
import { useFinancePlanning } from '../../state/useFinancePlanning'
import type { FinanceGoal, FinanceGoalData } from '../../types/finance'
import { FinancialAmount } from '../privacy/FinancialAmount'
import { Button } from '../ui/button'
import { Dialog, DialogContent, DialogDescription, DialogTitle, DialogTrigger } from '../ui/dialog'
import { InlineError } from '../ui/InlineError'

const amountInput = (amountSen: number) => `${Math.floor(amountSen / 100)}.${String(amountSen % 100).padStart(2, '0')}`

export function FinanceGoalsPanel() {
  const planning = useFinancePlanning()
  const active = planning.goals.filter((goal) => goal.status === 'active')
  const archived = planning.goals.filter((goal) => goal.status === 'archived')
  return <section className="dashboard-card p-5 sm:p-6" aria-labelledby="finance-goals-heading">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="section-label">Savings plans</p><h2 id="finance-goals-heading" className="mt-1 text-lg font-semibold">Goals</h2><p className="mt-2 text-sm text-[var(--text-secondary)]">Allocations reserve money toward goals. They are not expenses.</p></div><GoalEditor /></div>
    {planning.status === 'loading' ? <p className="mt-4 text-sm text-[var(--text-muted)]">Loading goals…</p> : planning.status === 'error' ? <p role="alert" className="mt-4 rounded-xl bg-[var(--danger-wash)] p-4 text-sm">Goals are temporarily unavailable.</p> : active.length === 0 ? <p className="mt-4 rounded-xl border border-dashed border-[var(--border-subtle)] p-4 text-sm text-[var(--text-muted)]">No active goals. Add one when you have something specific to save toward.</p> : <div className="mt-4 space-y-3">{active.map((goal) => <GoalRow key={goal.id} goal={goal} />)}</div>}
    {archived.length > 0 && <details className="mt-4"><summary className="min-h-10 cursor-pointer py-2 text-sm font-semibold text-[var(--text-secondary)]">Archived goals ({archived.length})</summary><div className="space-y-2">{archived.map((goal) => <div key={goal.id} className="flex items-center gap-3 rounded-xl border border-[var(--border-subtle)] p-3"><p className="min-w-0 flex-1 truncate text-sm font-semibold">{goal.name}</p><FinancialAmount amountSen={goal.allocatedAmountSen} interactive={false} className="text-sm" /><Button variant="ghost" onClick={() => void planning.setGoalArchived(goal, false)}><RotateCcw size={15} />Restore</Button></div>)}</div></details>}
  </section>
}

function GoalRow({ goal }: { goal: FinanceGoal }) {
  const planning = useFinancePlanning(); const progress = goalProgress(goal)
  return <article className="rounded-2xl border border-[var(--border-subtle)] bg-[var(--surface-secondary)] p-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><Target size={16} className="text-[var(--accent-soft)]" /><h3 className="truncate text-sm font-semibold">{goal.name}</h3></div><p className="mt-2 text-lg font-semibold"><FinancialAmount amountSen={goal.allocatedAmountSen} /> <span className="text-xs font-normal text-[var(--text-muted)]">of <FinancialAmount amountSen={goal.targetAmountSen} interactive={false} /></span></p>{goal.targetDate && <p className="mt-1 flex items-center gap-1 text-xs text-[var(--text-muted)]"><CalendarDays size={13} />Target {new Intl.DateTimeFormat('en-MY', { dateStyle: 'medium' }).format(new Date(goal.targetDate))}</p>}</div><div className="flex flex-wrap gap-2"><ContributionDialog goal={goal} /><GoalEditor goal={goal} /><Button variant="ghost" onClick={() => void planning.setGoalArchived(goal, true)}><Archive size={15} />Archive</Button></div></div>
    <div className="mt-3 h-2 overflow-hidden rounded-full bg-[var(--surface-primary)]"><div className="h-full rounded-full bg-[var(--accent-primary)]" style={{ width: `${progress}%` }} /></div><p className="mt-1 text-right text-xs text-[var(--text-muted)]">{Math.round(progress)}% funded</p>
  </article>
}

function GoalEditor({ goal }: { goal?: FinanceGoal }) {
  const planning = useFinancePlanning(); const privacy = usePrivacyLock(); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const [name, setName] = useState(''); const [target, setTarget] = useState(''); const [initial, setInitial] = useState(''); const [targetDate, setTargetDate] = useState('')
  function changeOpen(next: boolean) { if (saving) return; if (next && privacy.locked) { privacy.requestUnlock(); return } setOpen(next); setError(''); if (next) { setName(goal?.name ?? ''); setTarget(goal ? amountInput(goal.targetAmountSen) : ''); setInitial(''); setTargetDate(goal?.targetDate?.slice(0, 10) ?? '') } }
  async function submit(event: FormEvent) { event.preventDefault(); const amount = parseRinggitToSen(target); const initialSen = initial ? parseRinggitToSen(initial) : 0; if (!name.trim() || amount === null || initialSen === null) { setError('Enter a name and valid amounts above RM 0.'); return } const data: FinanceGoalData = { name: name.trim(), targetAmountSen: amount, targetDate: targetDate || null, status: goal?.status ?? 'active' }; setSaving(true); try { if (goal) await planning.updateGoal(goal, data); else await planning.createGoal(data, initialSen); setOpen(false) } catch { setError('The goal could not be saved.') } finally { setSaving(false) } }
  return <Dialog open={open} onOpenChange={changeOpen}><DialogTrigger asChild><Button variant="secondary">{goal ? 'Edit' : <><Plus size={16} />Add goal</>}</Button></DialogTrigger><DialogContent closeDisabled={saving}><DialogTitle className="pr-12 text-xl font-semibold">{goal ? 'Edit goal' : 'Create goal'}</DialogTitle><DialogDescription className="mt-2 text-sm text-[var(--text-secondary)]">Targets and allocations stay separate from actual spending.</DialogDescription><form className="mt-5 space-y-4" onSubmit={(event) => void submit(event)}><label className="form-label">Name<input autoFocus className="form-control mt-1" maxLength={80} value={name} onChange={(event) => setName(event.target.value)} /></label><label className="form-label">Target amount (RM)<input className="form-control mt-1" inputMode="decimal" value={target} onChange={(event) => setTarget(event.target.value)} /></label>{!goal && <label className="form-label">Already saved (RM, optional)<input className="form-control mt-1" inputMode="decimal" value={initial} onChange={(event) => setInitial(event.target.value)} /><span className="mt-1 block text-xs font-normal text-[var(--text-muted)]">Opening balance for progress; it is not counted as this month’s allocation.</span></label>}<label className="form-label">Target date (optional)<input className="form-control mt-1" type="date" value={targetDate} onChange={(event) => setTargetDate(event.target.value)} /></label>{error && <InlineError message={error} />}<div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button type="button" variant="ghost" onClick={() => changeOpen(false)}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? 'Saving…' : 'Save goal'}</Button></div></form></DialogContent></Dialog>
}

function ContributionDialog({ goal }: { goal: FinanceGoal }) {
  const planning = useFinancePlanning(); const privacy = usePrivacyLock(); const [open, setOpen] = useState(false); const [amount, setAmount] = useState(''); const [date, setDate] = useState(() => new Date().toISOString().slice(0, 10)); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  function changeOpen(next: boolean) { if (saving) return; if (next && privacy.locked) { privacy.requestUnlock(); return } setOpen(next); if (next) { setAmount(''); setDate(new Date().toISOString().slice(0, 10)) } setError('') }
  async function submit(event: FormEvent) { event.preventDefault(); const amountSen = parseRinggitToSen(amount); if (amountSen === null || !date) { setError('Enter a valid amount and date.'); return } setSaving(true); try { await planning.contributeToGoal(goal, amountSen, new Date(`${date}T12:00:00`)); setOpen(false) } catch { setError('The allocation could not be saved.') } finally { setSaving(false) } }
  return <Dialog open={open} onOpenChange={changeOpen}><DialogTrigger asChild><Button>Allocate</Button></DialogTrigger><DialogContent closeDisabled={saving}><DialogTitle className="pr-12 text-xl font-semibold">Allocate to {goal.name}</DialogTitle><DialogDescription className="mt-2 text-sm text-[var(--text-secondary)]">This reserves money toward the goal. It will not create an expense.</DialogDescription><form className="mt-5 space-y-4" onSubmit={(event) => void submit(event)}><label className="form-label">Amount (RM)<input autoFocus className="form-control mt-1" inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><label className="form-label">Allocation date<input className="form-control mt-1" type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label>{error && <InlineError message={error} />}<div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button type="button" variant="ghost" onClick={() => changeOpen(false)}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? 'Allocating…' : 'Confirm allocation'}</Button></div></form></DialogContent></Dialog>
}
