import { Archive, Plus, RotateCcw } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { expenseCategoryOptions } from '../../domain/expense'
import type { BudgetPlanSummary } from '../../domain/financePlanning'
import { parseRinggitToSen } from '../../lib/format'
import { usePrivacyLock } from '../../privacy/usePrivacyLock'
import { useFinancePlanning } from '../../state/useFinancePlanning'
import type { FinanceBudget, FinanceBudgetData } from '../../types/finance'
import type { ExpenseCategory } from '../../types/records'
import { MoneySettingsDialog } from '../dashboard/MoneySettingsDialog'
import { FinancialAmount } from '../privacy/FinancialAmount'
import { Button } from '../ui/button'
import { Dialog, DialogContent, DialogDescription, DialogTitle, DialogTrigger } from '../ui/dialog'
import { InlineError } from '../ui/InlineError'

const amountInput = (amountSen: number) => `${Math.floor(amountSen / 100)}.${String(amountSen % 100).padStart(2, '0')}`

export function FinanceBudgetsPanel({ summary }: { summary: BudgetPlanSummary }) {
  const planning = useFinancePlanning()
  return <section className="dashboard-card p-5 sm:p-6" aria-labelledby="finance-budgets-heading">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="section-label">Monthly plan</p><h2 id="finance-budgets-heading" className="mt-1 text-lg font-semibold">Budget pots</h2><p className="mt-2 text-sm text-[var(--text-secondary)]">Category spending comes from confirmed expenses.</p></div><BudgetEditor /></div>
    <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric label="Total budget" amount={summary.totalBudgetSen} /><Metric label="Allocated" amount={summary.allocatedBudgetSen} /><Metric label="Unallocated" amount={summary.unallocatedBudgetSen} /><Metric label="Spent" amount={summary.spentSen} /></div>
    <div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-secondary)] p-3"><div><p className="text-sm font-semibold">Overall monthly spending limit</p><p className="text-xs text-[var(--text-muted)]">Optional; pots can also stand alone.</p></div><MoneySettingsDialog kind="budget" /></div>
    {planning.status === 'loading' ? <p className="mt-4 text-sm text-[var(--text-muted)]">Loading budget pots…</p> : summary.active.length === 0 ? <p className="mt-4 rounded-xl border border-dashed border-[var(--border-subtle)] p-4 text-sm text-[var(--text-muted)]">No budget pots. The overall limit still works on its own.</p> : <div className="mt-4 space-y-3">{summary.active.map((item) => <article key={item.budget.id} className={`rounded-2xl border p-4 ${item.isOverspent ? 'border-[var(--warning-border)] bg-[var(--warning-wash)]' : 'border-[var(--border-subtle)] bg-[var(--surface-secondary)]'}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-sm font-semibold">{item.budget.name}</h3><p className="mt-1 text-xs text-[var(--text-muted)]">{item.budget.category ? expenseCategoryOptions.find((option) => option.value === item.budget.category)?.label : 'Planning-only · no category linked'}</p></div><div className="flex gap-2"><BudgetEditor budget={item.budget} /><Button variant="ghost" onClick={() => void planning.setBudgetArchived(item.budget, true)}><Archive size={15} />Archive</Button></div></div><div className="mt-3 flex flex-wrap gap-x-5 gap-y-1 text-sm"><span><strong><FinancialAmount amountSen={item.budget.monthlyAmountSen} interactive={false} /></strong> budget</span>{item.spentSen === null ? <span className="text-[var(--text-muted)]">Link a category to derive spending</span> : <><span><FinancialAmount amountSen={item.spentSen} interactive={false} /> spent</span><span className={item.isOverspent ? 'text-[var(--warning)]' : ''}><FinancialAmount amountSen={item.remainingSen ?? 0} interactive={false} /> remaining</span></>}</div></article>)}</div>}
    {summary.archived.length > 0 && <details className="mt-4"><summary className="min-h-10 cursor-pointer py-2 text-sm font-semibold text-[var(--text-secondary)]">Archived budgets ({summary.archived.length})</summary><div className="space-y-2">{summary.archived.map((budget) => <div key={budget.id} className="flex items-center gap-3 rounded-xl border border-[var(--border-subtle)] p-3"><p className="min-w-0 flex-1 truncate text-sm font-semibold">{budget.name}</p><FinancialAmount amountSen={budget.monthlyAmountSen} interactive={false} className="text-sm" /><Button variant="ghost" onClick={() => void planning.setBudgetArchived(budget, false)}><RotateCcw size={15} />Restore</Button></div>)}</div></details>}
  </section>
}

function Metric({ label, amount }: { label: string; amount: number | null }) { return <div className="rounded-xl bg-[var(--surface-secondary)] p-3"><p className="text-[0.68rem] font-semibold uppercase tracking-wide text-[var(--text-muted)]">{label}</p><p className="mt-1 truncate text-sm font-semibold">{amount === null ? 'Not set' : <FinancialAmount amountSen={amount} interactive={false} />}</p></div> }

function BudgetEditor({ budget }: { budget?: FinanceBudget }) {
  const planning = useFinancePlanning(); const privacy = usePrivacyLock(); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [name, setName] = useState(''); const [amount, setAmount] = useState(''); const [category, setCategory] = useState<ExpenseCategory | ''>('')
  function changeOpen(next: boolean) { if (saving) return; if (next && privacy.locked) { privacy.requestUnlock(); return } setOpen(next); setError(''); if (next) { setName(budget?.name ?? ''); setAmount(budget ? amountInput(budget.monthlyAmountSen) : ''); setCategory(budget?.category ?? '') } }
  async function submit(event: FormEvent) { event.preventDefault(); const amountSen = parseRinggitToSen(amount); if (!name.trim() || amountSen === null) { setError('Enter a name and valid monthly amount.'); return } const data: FinanceBudgetData = { name: name.trim(), monthlyAmountSen: amountSen, category: category || null, status: budget?.status ?? 'active' }; setSaving(true); try { if (budget) await planning.updateBudget(budget, data); else await planning.createBudget(data); setOpen(false) } catch { setError('The budget pot could not be saved.') } finally { setSaving(false) } }
  return <Dialog open={open} onOpenChange={changeOpen}><DialogTrigger asChild><Button variant="secondary">{budget ? 'Edit' : <><Plus size={16} />Add pot</>}</Button></DialogTrigger><DialogContent closeDisabled={saving}><DialogTitle className="pr-12 text-xl font-semibold">{budget ? 'Edit budget pot' : 'Create budget pot'}</DialogTitle><DialogDescription className="mt-2 text-sm text-[var(--text-secondary)]">Linking a category lets EdenOS derive spending from confirmed expenses.</DialogDescription><form className="mt-5 space-y-4" onSubmit={(event) => void submit(event)}><label className="form-label">Name<input autoFocus className="form-control mt-1" maxLength={80} value={name} onChange={(event) => setName(event.target.value)} /></label><label className="form-label">Monthly amount (RM)<input className="form-control mt-1" inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><label className="form-label">Expense category (optional)<select className="form-control mt-1" value={category} onChange={(event) => setCategory(event.target.value as ExpenseCategory | '')}><option value="">No category · planning only</option>{expenseCategoryOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>{error && <InlineError message={error} />}<div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button type="button" variant="ghost" onClick={() => changeOpen(false)}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? 'Saving…' : 'Save budget'}</Button></div></form></DialogContent></Dialog>
}
