import { Activity, CircleAlert, Dumbbell } from 'lucide-react'
import { useMemo, type ReactNode } from 'react'
import { Button } from '../components/ui/button'
import { formatLongDate } from '../lib/date'
import { formatDistance, formatDuration } from '../lib/format'
import { selectExerciseDashboard } from '../selectors/exerciseDashboardSelectors'
import { useRecords } from '../state/useRecords'
import { useUserSettings } from '../state/useUserSettings'
import { useLocalReferenceDate } from '../hooks/useLocalReferenceDate'

export function ExercisePage({ onOpenRecords }: { onOpenRecords: () => void }) {
  const records = useRecords(); const { settings } = useUserSettings(); const referenceDate = useLocalReferenceDate()
  const summary = useMemo(() => selectExerciseDashboard(records.exerciseRecords, settings.bodyWeightKg, referenceDate), [records.exerciseRecords, referenceDate, settings.bodyWeightKg])
  if (records.exerciseStatus === 'error') return <Page><div role="alert" className="dashboard-card p-6"><CircleAlert className="text-[var(--danger)]" /><h2 className="mt-3 text-lg font-semibold">Exercise unavailable</h2><p className="mt-2 text-sm text-[var(--text-secondary)]">{records.exerciseError}</p><Button className="mt-4" onClick={records.retryExerciseSubscription}>Retry</Button></div></Page>
  return <Page>
    <header><p className="section-label text-[var(--accent-teal)]">Movement</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Exercise</h1><p className="mt-2 text-sm text-[var(--text-secondary)]">Your weekly sessions, time, and activity mix.</p></header>
    <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Weekly sessions" value={String(summary.sessions)} detail={summary.durationComparisonPercent === null ? 'No prior-week comparison' : `${summary.durationComparisonPercent >= 0 ? '+' : ''}${summary.durationComparisonPercent}% duration vs last week`} /><Metric label="Weekly duration" value={formatDuration(summary.durationSeconds)} detail={summary.previousDurationSeconds ? `${formatDuration(summary.previousDurationSeconds)} last week` : 'Current local week'} /><Metric label="Total distance" value={summary.distanceMetres ? formatDistance(summary.distanceMetres) : '—'} detail="Where recorded" /><Metric label="Reported Calories" value={summary.reportedCaloriesKcal ? `${Math.round(summary.reportedCaloriesKcal)} kcal` : '—'} detail="Source-reported only" /></section>
    <section className="dashboard-card mt-4 p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="section-label">MET Estimated Calories</p><p className="metric-value mt-2 text-2xl font-semibold">{summary.estimatedCaloriesKcal ? `${summary.estimatedCaloriesKcal} kcal` : '—'}</p></div><p className="max-w-sm text-xs leading-5 text-[var(--text-muted)]">Estimated from activity, body weight, and duration for sessions without source-reported calories. Kept separate from device-reported values.</p></div></section>
    <div className="mt-4 grid gap-4 lg:grid-cols-[1fr_1.15fr]">
      <section className="dashboard-card p-5"><h2 className="section-label">Activity by duration</h2>{summary.activities.length ? <div className="mt-5 space-y-4">{summary.activities.map((item) => <div key={item.activity}><div className="flex justify-between text-sm"><span>{item.activity}</span><span>{formatDuration(item.durationSeconds)}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[var(--surface-secondary)]"><div className="h-full rounded-full bg-[var(--accent-teal)]" style={{ width: `${item.percentage}%` }} /></div></div>)}</div> : <Empty />}</section>
      <section className="dashboard-card p-5"><div className="flex items-center justify-between"><h2 className="section-label">Recent Workouts</h2><button type="button" onClick={onOpenRecords} className="text-sm font-semibold text-[var(--accent-soft)]">View Records</button></div>{summary.recent.length ? <ul className="mt-3 divide-y divide-[var(--border-subtle)]">{summary.recent.map((item) => { const reported = item.reportedActiveCaloriesKcal ?? item.reportedTotalCaloriesKcal; return <li key={item.id} className="flex gap-3 py-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[var(--accent-teal-wash)] text-[var(--accent-teal)]"><Dumbbell size={17} /></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">{item.activity}</span><span className="text-xs text-[var(--text-muted)]">{formatLongDate(item.occurredAt)} · {formatDuration(item.durationSeconds)}{item.distanceMetres ? ` · ${formatDistance(item.distanceMetres)}` : ''}</span></span>{reported !== undefined && <span className="text-right text-xs text-[var(--text-secondary)]"><strong className="block text-sm">{Math.round(reported)} kcal</strong>Reported</span>}</li>})}</ul> : <Empty />}</section>
    </div>
  </Page>
}
function Page({ children }: { children: ReactNode }) { return <div className="core-page mx-auto w-full max-w-[80rem] px-4 py-5 sm:px-6 lg:px-8">{children}</div> }
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className="dashboard-card p-5"><p className="section-label">{label}</p><p className="metric-value mt-3 text-2xl font-semibold">{value}</p><p className="mt-2 text-xs text-[var(--text-muted)]">{detail}</p></article> }
function Empty() { return <div className="mt-5 flex items-center gap-2 rounded-xl border border-dashed border-[var(--border-subtle)] p-4 text-sm text-[var(--text-muted)]"><Activity size={16} />No exercise records yet.</div> }
